SELECT A.USER_ID, A.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS A
INNER JOIN USED_GOODS_BOARD AS B ON A.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY A.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES